name: cos upload
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ main ]

jobs:
  
  cos-action:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v3
      with:
        path: main
        submodules: 'recursive'
    - name: Compress Images
      uses: calibreapp/image-actions@main
      with:
        githubToken: ${{ secrets.GITHUB_TOKEN }}
    - name: upload
      uses: haloislet/cos-action@v2
      with:
        COMMAND: coscmd upload -r ./ / --include "*.webp"
        SECRET_ID: ${{ secrets.SECRET_ID }}
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
        BUCKET: ${{ secrets.BUCKET }}
        REGION: ${{ secrets.REGION }}
