name: cos upload
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ main ]

jobs:
  
  cos-action:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v3
      with:
        path: main
        submodules: 'recursive'
    - name: upload
      uses: haloislet/cos-action@v2
      with:
        COMMAND: coscmd upload -r ./main/Arknight-Images/avg/backgrounds /avg/backgrounds
        SECRET_ID: ${{ secrets.SECRET_ID }}
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
        BUCKET: ${{ secrets.BUCKET }}
        REGION: ${{ secrets.REGION }}
    - name: upload
      uses: haloislet/cos-action@v2
      with:
        COMMAND: coscmd upload -r ./main/Arknight-Images/avg/images /avg/images
        SECRET_ID: ${{ secrets.SECRET_ID }}
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
        BUCKET: ${{ secrets.BUCKET }}
        REGION: ${{ secrets.REGION }}
